name: Deploy Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy API and Wait for Response
        run: |
          HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" -X POST "https://api.alltime.in.th/deploy/blackjack" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
          -d '{"tag": "${{ github.event.release.tag_name }}"}')

          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "✅ Deploy triggered successfully!"
          else
            echo "❌ Deploy failed with status code: $HTTP_STATUS"
            exit 1
          fi